apiVersion: apps/v1
kind: Deployment
metadata:
  name: popcorn-port-app
  labels:
    app: popcorn-port-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: popcorn-port-app
  template:
    metadata:
      labels:
        app: popcorn-port-app
    spec:
      containers:
      - name: popcorn-port-app
        image: soumyaranjanswainteleglobal/popcorn-port-jenkins:latest
        ports:
        - containerPort: 80
